### ISSUE TITLE
Unknown format 6?

### ISSUE THREAD

**Issue by mubix** [ragibson/Steganography#1]
python WavSteg.py -r -s /testing.wav -o wave.txt -n 1 -b 1000
Ran into an error during execution. Check input and try again.

unknown format: 6

**Comment by ragibson** [comment]
I'm using Python's wave module which only supports a few types of WAV files.

In particular, your file seems to be of type WAVE_FORMAT_ALAW which would need to be converted first (e.g. with ffmpeg).
