### ISSUE TITLE
stegolsb not recognized as command

### ISSUE THREAD

**Issue by MrMyastan** [ragibson/Steganography#10]
I used `pip3 install stego-lsb` to install and everything seemed to go fine but in windows command prompt I'm getting
```
'stegolsb' is not recognized as an internal or external command,
operable program or batch file.
```
Anyone know how to fix that? 
If it helps I'm using the windows store install of Python 3.8 and didn't have wheel installed when I installed stegolsb
Thanks much!

**Comment by ragibson** [comment]
Strange, does `pip3 show stego-lsb` show anything?

I can test this on a Windows machine after work today (~30 minutes).

**Comment by ragibson** [comment]
I cannot replicate this on my Windows machine. A few questions:

1. Does `import stego_lsb` work in python?
2. Can you try uninstalling and reinstalling the package via pip3?
3. If that doesn't work, can you copy the complete output of `pip3 list` here and tell me the exact version of Python you're using?

**Comment by MrMyastan** [comment]
`pip3 show stego-lsb` outputs:
```Name: stego-lsb
Version: 1.3.1
Summary: stego lsb
Home-page: https://github.com/ragibson/Steganography
Author: Ryan Gibson
Author-email: ryanalexandergibson@gmail.com
License: MIT
Location: c:\users\admir\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
Requires: Pillow, numpy, Click
Required-by:
```

`import stego_lsb` is marked as an unresolved import by vscode but running it doesn't cause an exception

uninstalling and reinstalling via pip3 I think shows the issue
```  
WARNING: The script stegolsb.exe is installed in 'C:\Users\admir\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
Should I just make a shortcut?

**Comment by ragibson** [comment]
Yeah, you should add that scripts directory to your PATH. I'm somewhat surprised Windows' installation of Python didn't do that automatically.

**Comment by MrMyastan** [comment]
weird
well, adding it to the path worked! thanks much
